name: Django Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clona el repositori
        uses: actions/checkout@v3

      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instal·la dependències
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fes les migracions
        run: |
          python manage.py migrate

      - name: Executa els tests
        run: |
          python manage.py test
